### ISSUE TITLE
Missing libraries when building widelands using bundle-dylibs 

### ISSUE THREAD

**Issue by klaus-halfmann** [imrehorvath/bundle-dylibs#3] opened 2024-10-20 11:28 UTC
Hello @imrehorvath.

Once Upon a time I copied your script to our Repo at 
[Widelands ... bundle-dylibs.sh](https://github.com/widelands/widelands/blob/5a9087b08ab9bbc48795ff0f7f1f370f60108b1a/utils/macos/bundle-dylibs.sh) but since some time the .app files we are building are missing some transient
libraries, See: https://github.com/widelands/widelands/issues/6444 

I checked your recent changes and found only some minor improvements.
* This may affect other project using this script, too.
* My assumption is: some recent change in the macOS tools causes this.

This is just a mirror of our bug for now, in case we find a solution I will try to update this Issue.

**Comment by imrehorvath** [comment] 2024-10-22 14:19
Hello @klaus-halfmann 

Thanks for reaching out with this. I would recommend using the most recent version (HEAD) of the script as it contains some crucial fixes and compatibility improvements since the version you copied.

Looking at the version you referenced I noticed it's an older version, that definitely had issues with paths with eg. space in them.

**Comment by klaus-halfmann** [comment] 2024-10-22 17:23
Hello @imrehorvath ,

As you can See I went back to [dylibbundler](https://github.com/auriamg/macdylibbundler/). I even updated your script as suggested by [shellcheck](https://www.shellcheck.net) but still the number of libraries is different? Please check my bug  and the related PR. You can find my version of your script at [bundle-dylibs.sh]( https://github.com/widelands/widelands/blob/fix_macos_bundles2/utils/macos/bundle-dylibs.sh)

My assumption is that some recent change in the OSX-SDK makes your variant fail.

As we currently have an Issue building mac os, it make take some time until this was validated.

**Comment by imrehorvath** [comment] 2024-10-23 10:19
Hello @klaus-halfmann ,

Please note, that the `list_dylibs` function is for obtaining the list of extra dynamic libraries on your system, which needs to be bundled into your application bundle to make your app portable.

```
list_dylibs() {
    local file="$1"
    echo $(otool -L "$file" |\
	       sed -n 's/^[[:space:]]*\(.*\) (.*$/\1/p' |\
	       sed -e '/^\/System/d' -e '/^\/usr\/lib/d' -e '/^@/d')
}
```
It uses the CLT tool `otool` to obtain the list of used dynamic libraries. Then it filters the output so only the extra libraries remain in the list, using `sed`.

How we decide which are the extra libraries used? By assuming all the entries starting with `/System/` or `/usr/lib` are standard libraries as these are standard directory locations on macOS and assumed to be present with desired content (libraries). So these entries gets excluded from processing along with the entries with `@` by design. The remaining lines are to be processed further.

I hope this gives you a hint in resolving the build issue in your project.

**Comment by imrehorvath** [comment] 2024-10-23 12:09
@klaus-halfmann to get a sense of its working, you can try the following.

Inspect the output of `otool`:
`otool -L /path/to/file`

Inspect what remains after filtering (subject for further processing in the main script):
```
otool -L /path/to/file |\
               sed -n 's/^[[:space:]]*\(.*\) (.*$/\1/p' |\
               sed -e '/^\/System/d' -e '/^\/usr\/lib/d' -e '/^@/d'
```
I hope this helps you with your issue-resolution.

**Comment by imrehorvath** [comment] 2024-10-23 18:10
@klaus-halfmann provided you use the current script from my repo and after using it, ending up with an app bundle with executables and/or dylibs failing to load on the target, I can think of two scenarios.

1. The referenced dylibs are either in `/System` or `/usr/lib` on the build system but absent on the target.
2. The offending dylibs are referenced using a `@` tag are not at the referred location.

You can verify both with the above example. I hope it helps you with your resolution.

**Comment by imrehorvath** [comment] 2024-10-24 07:28
For an actual reproducible issue with this tool, please open an issue with detailed description on how to trigger the problem, what is the problem and what would be the desired behavior/output. If it's clearly visible that the tool is at fault, I'm willing to look into it.

However debugging a project, that uses (some version) of this tool, is out of the scope of this project.

As no actual issue is visible with the tool itself at the moment, I close this issue.

**Closed as completed by imrehorvath** 2024-10-24 07:28 UTC
